### ISSUE TITLE
No update on MX-records after initial test

### ISSUE THREAD

**Issue by yhagger** [einaros/starttls.info#1]
If a domain changes MX-records starttls.info does recheck for new mx-records the next search.

**Comment by tripsjgh** [comment]
I can confirm this behavior.  It's clear that there is an MX lookup for a domain at the first appearance so why not always get MX records via some try/catch logic linked to the "retest" button.  Better yet, don't even cache the result of the initial fetch that way every test forced the use of the MX lookup logic already in place.  This of course is all predicated on the notion that the MX lookup data is being stored locally in something like MongoD or Redis and this is not the fault of a caching-only DNS server that is never updating.

**Comment by openbrian** [comment]
This bug is affecting me too.

**Comment by openbrian** [comment]
Any update on this?

**Comment by einaros** [comment]
This should be fixed now. Please re-check. Also, major apologies for the delay!

**Comment by yhagger** [comment]
@einaros Thanks. It works after I click the reset cache button to the upper right.

**Comment by einaros** [comment]
Great!
