### ISSUE TITLE
Error: Could not connect (timeout) does not offer any helpful details for troubleshooting

### ISSUE THREAD

**Issue by sysfu** [einaros/starttls.info#9]
I'm trying to use starttls.info to test the mail server for domain sysfu.com but every test fails with the message `Error: Could not connect (timeout)`

I do not see any connection attempts in either the firewall or mail server logs, so I am at a loss as for how to troubleshoot without further info.

**Comment by sysfu** [comment]
Also, the mail server in running OpenBSDs pf + spamd, so maybe the greylisting temporary failure is causing the test to fail.

**Comment by einaros** [comment]
Servers with aggressive filters / spam checking / very restrictive configs will likely block the probe server at present. I doubt I'll be able to address this until I've completed the completely fresh probing system (which I've been working on for more than 6mo now).

**Comment by sysfu** [comment]
If you could please publish the IP address(es) where the starttls.info tests originate from, I can add these to the spamd bypass table.

**Comment by sysfu** [comment]
I got the test to work after clicking on the 'reset cache' link. For anyone else running spamd on OpenBSD, make sure to add the IP address for host probe1.starttls.info (95.85.50.161) to your /etc/mail/nospamd table
